/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns all items. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClutterStock.Contracts.Items.ItemResponse"][];
                    };
                };
                /** @description Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        /** @description Creates a new item. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClutterStock.Contracts.Items.AddItemRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClutterStock.Contracts.Items.ItemResponse"];
                    };
                };
                /** @description Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns a single item by id. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClutterStock.Contracts.Items.ItemResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        /** @description Updates an existing item by id. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClutterStock.Contracts.Items.UpdateItemRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClutterStock.Contracts.Items.ItemResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        /** @description Deletes an item by id. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns all locations. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClutterStock.Contracts.Locations.LocationResponse"][];
                    };
                };
                /** @description Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        /** @description Creates a new location. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClutterStock.Contracts.Locations.AddLocationRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClutterStock.Contracts.Locations.LocationResponse"];
                    };
                };
                /** @description Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns a single location by id. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClutterStock.Contracts.Locations.LocationResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        /** @description Updates an existing location by id. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClutterStock.Contracts.Locations.UpdateLocationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClutterStock.Contracts.Locations.LocationResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        /** @description Deletes a location by id. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns all rooms. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClutterStock.Contracts.Rooms.RoomResponse"][];
                    };
                };
                /** @description Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        /** @description Creates a new room. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClutterStock.Contracts.Rooms.AddRoomRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClutterStock.Contracts.Rooms.RoomResponse"];
                    };
                };
                /** @description Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns a single room by id. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClutterStock.Contracts.Rooms.RoomResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        /** @description Updates an existing room by id. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClutterStock.Contracts.Rooms.UpdateRoomRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClutterStock.Contracts.Rooms.RoomResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        /** @description Deletes a room by id. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Test endpoint that returns a greeting. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
                /** @description Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request body for creating an item. */
        "ClutterStock.Contracts.Items.AddItemRequest": {
            /**
             * Format: int32
             * @description Id of the room this item belongs to.
             * @example 1
             */
            roomId?: number;
            /**
             * @description Display name of the item.
             * @example Vintage Lamp
             */
            name?: string | null;
            /**
             * @description Optional longer description.
             * @example Brass table lamp, 1980s
             */
            description?: string | null;
            /**
             * @description Optional category (e.g. Electronics, Furniture).
             * @example Electronics
             */
            category?: string | null;
            /**
             * @description Optional free-form notes.
             * @example Needs new shade
             */
            notes?: string | null;
        };
        /** @description Response payload for an item. */
        "ClutterStock.Contracts.Items.ItemResponse": {
            /**
             * Format: int32
             * @description Unique identifier of the item.
             * @example 1
             */
            id?: number;
            /**
             * Format: int32
             * @description Id of the room this item belongs to.
             * @example 1
             */
            roomId?: number;
            /**
             * @description Display name of the item.
             * @example Vintage Lamp
             */
            name?: string | null;
            /**
             * @description Optional longer description.
             * @example Brass table lamp, 1980s
             */
            description?: string | null;
            /**
             * @description Optional category (e.g. Electronics, Furniture).
             * @example Electronics
             */
            category?: string | null;
            /**
             * @description Optional free-form notes.
             * @example Needs new shade
             */
            notes?: string | null;
            /**
             * Format: date-time
             * @description UTC timestamp when the item was created.
             * @example 2024-01-15T10:30:00Z
             */
            createdAtUtc?: string;
            /**
             * Format: date-time
             * @description UTC timestamp when the item was last updated.
             * @example 2024-02-01T14:00:00Z
             */
            updatedAtUtc?: string | null;
        };
        /** @description Request body for updating an item. Id is provided in the route. */
        "ClutterStock.Contracts.Items.UpdateItemRequest": {
            /**
             * Format: int32
             * @description Id of the room this item belongs to.
             * @example 1
             */
            roomId?: number;
            /**
             * @description Display name of the item.
             * @example Vintage Lamp
             */
            name?: string | null;
            /**
             * @description Optional longer description.
             * @example Brass table lamp, 1980s
             */
            description?: string | null;
            /**
             * @description Optional category (e.g. Electronics, Furniture).
             * @example Electronics
             */
            category?: string | null;
            /**
             * @description Optional free-form notes.
             * @example Needs new shade
             */
            notes?: string | null;
        };
        /** @description Request body for creating a location. */
        "ClutterStock.Contracts.Locations.AddLocationRequest": {
            /**
             * @description Display name of the location (e.g. home, office).
             * @example Home
             */
            name?: string | null;
            /**
             * @description Optional description of the location.
             * @example Main residence
             */
            description?: string | null;
        };
        /** @description Response payload for a location. */
        "ClutterStock.Contracts.Locations.LocationResponse": {
            /**
             * Format: int32
             * @description Unique identifier of the location.
             * @example 1
             */
            id?: number;
            /**
             * @description Display name of the location (e.g. home, office).
             * @example Home
             */
            name?: string | null;
            /**
             * @description Optional description of the location.
             * @example Main residence
             */
            description?: string | null;
            /**
             * Format: date-time
             * @description UTC timestamp when the location was created.
             * @example 2024-01-15T10:30:00Z
             */
            createdAtUtc?: string;
            /**
             * Format: date-time
             * @description UTC timestamp when the location was last updated.
             * @example 2024-02-01T14:00:00Z
             */
            updatedAtUtc?: string | null;
        };
        /** @description Request body for updating a location. Id is provided in the route. */
        "ClutterStock.Contracts.Locations.UpdateLocationRequest": {
            /**
             * @description Display name of the location (e.g. home, office).
             * @example Home
             */
            name?: string | null;
            /**
             * @description Optional description of the location.
             * @example Main residence
             */
            description?: string | null;
        };
        /** @description Request body for creating a room. */
        "ClutterStock.Contracts.Rooms.AddRoomRequest": {
            /**
             * Format: int32
             * @description Id of the parent location.
             * @example 1
             */
            locationId?: number;
            /**
             * @description Display name of the room (e.g. Living Room, Garage).
             * @example Living Room
             */
            name?: string | null;
            /**
             * @description Optional description of the room.
             * @example Main gathering space
             */
            description?: string | null;
        };
        /** @description Response payload for a room. */
        "ClutterStock.Contracts.Rooms.RoomResponse": {
            /**
             * Format: int32
             * @description Unique identifier of the room.
             * @example 1
             */
            id?: number;
            /**
             * Format: int32
             * @description Id of the parent location.
             * @example 1
             */
            locationId?: number;
            /**
             * @description Display name of the room (e.g. Living Room, Garage).
             * @example Living Room
             */
            name?: string | null;
            /**
             * @description Optional description of the room.
             * @example Main gathering space
             */
            description?: string | null;
            /**
             * Format: date-time
             * @description UTC timestamp when the room was created.
             * @example 2024-01-15T10:30:00Z
             */
            createdAtUtc?: string;
            /**
             * Format: date-time
             * @description UTC timestamp when the room was last updated.
             * @example 2024-02-01T14:00:00Z
             */
            updatedAtUtc?: string | null;
        };
        /** @description Request body for updating a room. Id is provided in the route. */
        "ClutterStock.Contracts.Rooms.UpdateRoomRequest": {
            /**
             * Format: int32
             * @description Id of the parent location.
             * @example 1
             */
            locationId?: number;
            /**
             * @description Display name of the room (e.g. Living Room, Garage).
             * @example Living Room
             */
            name?: string | null;
            /**
             * @description Optional description of the room.
             * @example Main gathering space
             */
            description?: string | null;
        };
        "Microsoft.AspNetCore.Mvc.ProblemDetails": {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
