name: "Continuous Integration (PR build)"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [opened, reopened, labeled, synchronize, ready_for_review]

permissions:
  contents: read
  checks: write
  pull-requests: write
  packages: read

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  pr-build:
    uses: hwinther/reusable-workflows/.github/workflows/pr-build.yml@v1
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    secrets: inherit
    with:
      node_enabled: true
      node_version: "24.x"
      node_working_directory: "frontend"
      node_changes_regex: "frontend/.*|backend/src/Api/openapi.json"
      node_extra_command: "npm run openapi-typescript"
      dotnet_enabled: true
      dotnet_version: "10.0.x"
      dotnet_working_directory: "backend"
      dotnet_solution_file: "ClutterStock.slnx"

  inspect-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"
          cache: true
          cache-dependency-path: "backend/**/packages.lock.json"

      - name: Restore
        working-directory: backend
        run: dotnet restore --locked-mode "ClutterStock.slnx"

      - name: Inspect code
        uses: muno92/resharper_inspectcode@v1
        #if: ${{ github.event_name == 'pull_request' && github.base_ref == 'main' }}
        with:
          workingDirectory: backend
          solutionPath: "ClutterStock.slnx"
          dotnetVersion: "10.0.x"
          failOnIssue: false
          solutionWideAnalysis: true
          include: |
            **.cs
          # ignoreIssueType: PropertyCanBeMadeInitOnly.Global
