name: "Stryker (Mutation Testing)"

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - main
  #   types: [opened, reopened, labeled, synchronize, ready_for_review]

concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: false

jobs:
  stryker:
    uses: hwinther/reusable-workflows/.github/workflows/stryker.yml@f72dbfff5f226a3fc3035daa2eb29dde3464582e # v1.62.0
    permissions:
      contents: read
      actions: write
    with:
      # Does not seem to work with MTP as of dotnet-stryker 4.14.0 - the process never completes
      run_dotnet_stryker: false
      run_node_stryker: true
      dotnet_version: 10.0.x
      solution_path: backend
      solution_name: ClutterStock.slnx
      node_version: 24.x
      node_working_directory: frontend
      mutation_level: Standard
      extra_arguments: "--diag"
      dotnet_artifact_name: github-pages-stryker-dotnet
      node_artifact_name: github-pages-stryker-node
